"use client";

// Hero -> REELS portal.
//
// REELS physically exists underneath ART, and the A's real crossbar is an
// SVG clipPath applied to the REELS layer — so the crossbar geometry
// decides which REELS pixels are visible. There is no portal element: if
// you delete the ART layer you still see REELS only inside the crossbar
// opening, and if you disable the clip-path the whole filmstrip appears.
//
// ART is drawn from the actual Dream Avenue outlines (see artGeometry.ts,
// generated by fonttools), not HTML text, so the crossbar path and the
// wordmark share one coordinate system. The SVG is placed so the rendered
// wordmark is identical in size and position to the hero's ART: the same
// 462 font-size at ART_SCALE_DEEP, centred on the stage, on the same
// baseline.
//
// Steps 1-6 of the spec only: geometry, layering and the mask. No
// expansion animation or ART fade yet.

import { useEffect, useRef, useState } from "react";
import {
  ART_SCALE_DEEP,
  ART_Y_DEEP,
  GLOW_STRENGTH,
  STAGE_H,
  STAGE_W,
} from "./HeroSection";
import { ART_VIEWBOX, CROSSBAR_CENTER, CROSSBAR_PATH, LETTER_PATHS } from "./artGeometry";

const SCROLL_LENGTH_VH = 220;

// -- Placing the SVG wordmark exactly where the HTML one used to sit. --
// The hero draws ART at font-size 462 scaled by ART_SCALE_DEEP, so one
// font unit (upm 1000) is this many stage units:
const ART_FONT_PX = 462 * ART_SCALE_DEEP;
const UNIT = ART_FONT_PX / 1000;
const ART_W = ART_VIEWBOX.width * UNIT;
// textAlign:center centres the advance width on the stage.
const ART_X = STAGE_W / 2 - ART_W / 2;
// Baseline of the HTML original: line-box top + 0.68em (the font's
// hhea ascent 0.75 plus the -0.07 half-leading of its 0.86 line-height).
const ART_BASELINE = 540 + ART_Y_DEEP - ((462 * 0.86) / 2) * ART_SCALE_DEEP + 0.68 * ART_FONT_PX;
// artGeometry's y is flipped so the baseline sits at viewBox height.
const ART_Y = ART_BASELINE - ART_VIEWBOX.height * UNIT;

// Crossbar centre in stage coordinates — the portal expands around this,
// never the SVG origin.
const PORTAL_CENTER_X = ART_X + CROSSBAR_CENTER.x * UNIT;
const PORTAL_CENTER_Y = ART_Y + CROSSBAR_CENTER.y * UNIT;

const ART_DEEP_G = 0.5 * GLOW_STRENGTH;

const REEL_BAND_HEIGHT = 430;
const REEL_FRAME_W = 300;
const REEL_FRAME_GAP = 24;
const REEL_FRAME_COUNT = 9;

export default function FilmstripEntry() {
  const stageRef = useRef<HTMLDivElement>(null);
  // Read once after mount (never during SSR) without a synchronous
  // setState in the effect body.
  const [debug, setDebug] = useState(false);
  useEffect(() => {
    const id = requestAnimationFrame(() =>
      setDebug(new URLSearchParams(window.location.search).get("debugPortal") === "true")
    );
    return () => cancelAnimationFrame(id);
  }, []);

  useEffect(() => {
    const fit = () => {
      const scale = Math.min(window.innerWidth / STAGE_W, window.innerHeight / STAGE_H);
      if (stageRef.current) stageRef.current.style.transform = `scale(${scale})`;
    };
    fit();
    window.addEventListener("resize", fit);
    return () => window.removeEventListener("resize", fit);
  }, []);

  const reelTotalW = REEL_FRAME_COUNT * (REEL_FRAME_W + REEL_FRAME_GAP) - REEL_FRAME_GAP;
  // The crossbar path lives in font units; this places it in stage space.
  const portalTransform = `translate(${ART_X} ${ART_Y}) scale(${UNIT})`;

  return (
    <div style={{ position: "relative", height: `${SCROLL_LENGTH_VH}vh`, zIndex: 1 }}>
      <div
        style={{
          position: "relative",
          height: "100vh",
          overflow: "hidden",
          background: "#000",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          ref={stageRef}
          style={{ position: "relative", width: STAGE_W, height: STAGE_H, flexShrink: 0 }}
        >
          {/* Mask geometry only — never painted. clipPathUnits is
              userSpaceOnUse so the path is in the same 1920x1080 stage
              coordinates as the layer it clips. */}
          <svg
            width="0"
            height="0"
            style={{ position: "absolute", pointerEvents: "none" }}
            aria-hidden
          >
            <defs>
              <clipPath id="reelsPortal" clipPathUnits="userSpaceOnUse">
                <path d={CROSSBAR_PATH} transform={portalTransform} />
              </clipPath>
              {/* Complement of the same geometry: ART paints everywhere
                  except the portal, so the crossbar is an actual opening
                  rather than a solid stroke covering the REELS behind it.
                  One shape drives both layers. */}
              <mask
                id="artPortalMask"
                maskUnits="userSpaceOnUse"
                maskContentUnits="userSpaceOnUse"
                x={0}
                y={0}
                width={STAGE_W}
                height={STAGE_H}
              >
                <rect x="0" y="0" width={STAGE_W} height={STAGE_H} fill="#fff" />
                <path d={CROSSBAR_PATH} transform={portalTransform} fill="#000" />
              </mask>
            </defs>
          </svg>

          {/* REELS layer — z-index 1, physically under ART, clipped by the
              crossbar so only the pixels inside the opening are visible. */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              zIndex: 1,
              clipPath: debug ? undefined : "url(#reelsPortal)",
            }}
          >
            <div
              style={{
                position: "absolute",
                left: (STAGE_W - reelTotalW) / 2,
                top: PORTAL_CENTER_Y - REEL_BAND_HEIGHT / 2,
                width: reelTotalW,
                height: REEL_BAND_HEIGHT,
                display: "flex",
                gap: REEL_FRAME_GAP,
              }}
            >
              {Array.from({ length: REEL_FRAME_COUNT }, (_, i) => (
                <div
                  key={i}
                  style={{
                    width: REEL_FRAME_W,
                    height: REEL_BAND_HEIGHT,
                    flexShrink: 0,
                    borderRadius: 18,
                    border: "3px solid rgba(255,255,255,0.92)",
                    // Bright enough to read as content through an opening
                    // only a few px tall — at 0.22/0.11 the filmstrip was
                    // indistinguishable from the black background.
                    background:
                      i % 2 === 0 ? "rgba(255,255,255,0.62)" : "rgba(255,255,255,0.4)",
                  }}
                />
              ))}
            </div>
          </div>

          {/* ART wordmark — z-index 3, real glyph outlines. */}
          <svg
            viewBox={`0 0 ${STAGE_W} ${STAGE_H}`}
            width={STAGE_W}
            height={STAGE_H}
            style={{ position: "absolute", inset: 0, zIndex: 3, pointerEvents: "none" }}
            aria-label="ART"
          >
            {/* Mask on an untransformed wrapper: with maskUnits
                userSpaceOnUse the mask geometry has to resolve in stage
                coordinates, not inside the group's own transform. */}
            <g mask={debug ? undefined : "url(#artPortalMask)"}>
            <g
              transform={portalTransform}
              fill="#fff"
              style={{
                filter: `drop-shadow(0 0 ${2 * ART_DEEP_G}px rgba(255,255,255,0.9)) drop-shadow(0 0 ${8 * ART_DEEP_G}px rgba(255,255,255,0.6)) drop-shadow(0 0 ${20 * ART_DEEP_G}px rgba(255,255,255,0.35))`,
              }}
            >
              <path d={LETTER_PATHS.A} />
              <path d={LETTER_PATHS.R} />
              <path d={LETTER_PATHS.T} />
            </g>
            </g>
          </svg>

          {debug && (
            <svg
              viewBox={`0 0 ${STAGE_W} ${STAGE_H}`}
              width={STAGE_W}
              height={STAGE_H}
              style={{ position: "absolute", inset: 0, zIndex: 5, pointerEvents: "none" }}
            >
              <path
                d={CROSSBAR_PATH}
                transform={portalTransform}
                fill="none"
                stroke="#0f0"
                strokeWidth={3}
              />
              <circle cx={PORTAL_CENTER_X} cy={PORTAL_CENTER_Y} r={8} fill="#f0f" />
            </svg>
          )}
        </div>
      </div>
    </div>
  );
}
