"use client";

// Hero -> REELS portal — static checkpoint, no animation.
//
// Exactly one reveal rule: a clip-path on the REELS layer. Nothing else
// is masked, nothing is drawn to represent the doorway. The crossbar
// geometry exists only inside <clipPath> and is never painted.
//
// REELS is painted above ART in z-order. That is what lets the single
// clip-path on REELS be the only reveal rule: with REELS underneath, ART's
// own crossbar stroke is opaque white and covers it, so REELS could only
// show through by also masking ART — a second mask, which the spec rules
// out. Clipped to a crossbar-sized aperture, REELS covers nothing except
// the inside of the crossbar, so ART still reads as the foreground and is
// itself completely untouched.
//
// ART is real Dream Avenue outline geometry (artGeometry.ts, generated by
// fonttools), placed to match the hero's ART exactly: same 462 font-size
// at ART_SCALE_DEEP, same centring, same baseline.

import { useEffect, useRef, useState } from "react";
import {
  ART_SCALE_DEEP,
  ART_Y_DEEP,
  GLOW_STRENGTH,
  STAGE_H,
  STAGE_W,
} from "./HeroSection";
import { ART_VIEWBOX, CROSSBAR_CENTER, CROSSBAR_PATH, LETTER_PATHS } from "./artGeometry";

const SCROLL_LENGTH_VH = 220;

// One font unit (upm 1000) in stage units, at the hero's ART size.
const ART_FONT_PX = 462 * ART_SCALE_DEEP;
const UNIT = ART_FONT_PX / 1000;
const ART_W = ART_VIEWBOX.width * UNIT;
const ART_X = STAGE_W / 2 - ART_W / 2;
const ART_BASELINE = 540 + ART_Y_DEEP - ((462 * 0.86) / 2) * ART_SCALE_DEEP + 0.68 * ART_FONT_PX;
const ART_Y = ART_BASELINE - ART_VIEWBOX.height * UNIT;

// Places the font-unit crossbar path into stage coordinates.
const PORTAL_TRANSFORM = `translate(${ART_X} ${ART_Y}) scale(${UNIT})`;
const PORTAL_CENTER_X = ART_X + CROSSBAR_CENTER.x * UNIT;
const PORTAL_CENTER_Y = ART_Y + CROSSBAR_CENTER.y * UNIT;

const ART_DEEP_G = 0.5 * GLOW_STRENGTH;

// REELS at its final scale — a full-width filmstrip, already in position.
const REEL_FRAME_W = 420;
const REEL_FRAME_H = 560;
const REEL_FRAME_GAP = 32;
const REEL_FRAME_COUNT = 7;
const REEL_FRAME_COLORS = [
  "#c9402f",
  "#2f6dc9",
  "#d9a52b",
  "#2fa86a",
  "#8a3fc0",
  "#d95f2b",
  "#2fb0c9",
];

export default function FilmstripEntry() {
  const stageRef = useRef<HTMLDivElement>(null);
  const [debug, setDebug] = useState(false);

  useEffect(() => {
    const id = requestAnimationFrame(() =>
      setDebug(new URLSearchParams(window.location.search).get("debugPortal") === "true")
    );
    return () => cancelAnimationFrame(id);
  }, []);

  useEffect(() => {
    const fit = () => {
      const scale = Math.min(window.innerWidth / STAGE_W, window.innerHeight / STAGE_H);
      if (stageRef.current) stageRef.current.style.transform = `scale(${scale})`;
    };
    fit();
    window.addEventListener("resize", fit);
    return () => window.removeEventListener("resize", fit);
  }, []);

  const reelTotalW = REEL_FRAME_COUNT * (REEL_FRAME_W + REEL_FRAME_GAP) - REEL_FRAME_GAP;
  const reelLeft = STAGE_W / 2 - reelTotalW / 2;
  const reelTop = STAGE_H / 2 - REEL_FRAME_H / 2;

  return (
    <div style={{ position: "relative", height: `${SCROLL_LENGTH_VH}vh`, zIndex: 1 }}>
      <div
        style={{
          position: "relative",
          height: "100vh",
          overflow: "hidden",
          background: "#000",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          ref={stageRef}
          style={{ position: "relative", width: STAGE_W, height: STAGE_H, flexShrink: 0 }}
        >
          {/* Clip geometry only. Never painted, never rendered as artwork. */}
          <svg width="0" height="0" style={{ position: "absolute" }} aria-hidden>
            <defs>
              <clipPath id="reelsPortal" clipPathUnits="userSpaceOnUse">
                <path d={CROSSBAR_PATH} transform={PORTAL_TRANSFORM} />
              </clipPath>
            </defs>
          </svg>

          {/* ART — untouched. No mask, no clip, no duplicated path. */}
          <svg
            viewBox={`0 0 ${STAGE_W} ${STAGE_H}`}
            width={STAGE_W}
            height={STAGE_H}
            style={{ position: "absolute", inset: 0, zIndex: 1, pointerEvents: "none" }}
            aria-label="ART"
          >
            <g
              transform={PORTAL_TRANSFORM}
              fill="#fff"
              style={{
                filter: `drop-shadow(0 0 ${2 * ART_DEEP_G}px rgba(255,255,255,0.9)) drop-shadow(0 0 ${8 * ART_DEEP_G}px rgba(255,255,255,0.6)) drop-shadow(0 0 ${20 * ART_DEEP_G}px rgba(255,255,255,0.35))`,
              }}
            >
              <path d={LETTER_PATHS.A} />
              <path d={LETTER_PATHS.R} />
              <path d={LETTER_PATHS.T} />
            </g>
          </svg>

          {/* REELS — complete section at final scale, already in position.
              The clip-path is the one and only reveal rule. */}
          <div
            id="reels-layer"
            style={{
              position: "absolute",
              inset: 0,
              zIndex: 2,
              clipPath: "url(#reelsPortal)",
            }}
          >
            <div
              id="reels-content"
              style={{
                position: "absolute",
                left: reelLeft,
                top: reelTop,
                width: reelTotalW,
                height: REEL_FRAME_H,
                display: "flex",
                gap: REEL_FRAME_GAP,
              }}
            >
              {Array.from({ length: REEL_FRAME_COUNT }, (_, i) => (
                <div
                  key={i}
                  style={{
                    width: REEL_FRAME_W,
                    height: REEL_FRAME_H,
                    flexShrink: 0,
                    borderRadius: 20,
                    border: "5px solid rgba(255,255,255,0.95)",
                    // Placeholder fills, deliberately saturated and varied:
                    // the aperture is only a few px tall at the crossbar's
                    // thinnest, so grey-on-black content would be
                    // indistinguishable from ART's own white stroke. Real
                    // REELS artwork replaces these. TODO: real content.
                    background: REEL_FRAME_COLORS[i % REEL_FRAME_COLORS.length],
                  }}
                />
              ))}
            </div>
          </div>

          {/* Debug only — separate from the clipPath, absent when off. */}
          {debug && (
            <svg
              viewBox={`0 0 ${STAGE_W} ${STAGE_H}`}
              width={STAGE_W}
              height={STAGE_H}
              style={{ position: "absolute", inset: 0, zIndex: 9, pointerEvents: "none" }}
            >
              <rect
                x={reelLeft}
                y={reelTop}
                width={reelTotalW}
                height={REEL_FRAME_H}
                fill="none"
                stroke="#ff0"
                strokeWidth={2}
                strokeDasharray="12 8"
              />
              <path
                d={CROSSBAR_PATH}
                transform={PORTAL_TRANSFORM}
                fill="none"
                stroke="#f00"
                strokeWidth={2}
              />
              <path
                d={CROSSBAR_PATH}
                transform={PORTAL_TRANSFORM}
                fill="none"
                stroke="#0ff"
                strokeWidth={1}
                strokeDasharray="6 4"
              />
              <circle cx={PORTAL_CENTER_X} cy={PORTAL_CENTER_Y} r={7} fill="#f0f" />
              <text x={40} y={60} fill="#0f0" fontSize={28} fontFamily="monospace">
                portalProgress 0.000
              </text>
            </svg>
          )}
        </div>
      </div>
    </div>
  );
}
